/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(alamouti_encode_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(301612462aaa7ad6fef465ae7433b811)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/alamouti_encode_cc.h>
// pydoc.h is automatically generated in the build directory
#include <alamouti_encode_cc_pydoc.h>

void bind_alamouti_encode_cc(py::module& m)
{

    using alamouti_encode_cc = gr::ieee802_11::alamouti_encode_cc;


    py::class_<alamouti_encode_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<alamouti_encode_cc>>(
        m, "alamouti_encode_cc", D(alamouti_encode_cc))

        .def(py::init(&alamouti_encode_cc::make), D(alamouti_encode_cc, make))


        ;
}
