/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_insert_preamble_tagged.h) */
/* BINDTOOL_HEADER_FILE_HASH(54ea8226055cc6bd1115e09d4cc3d29e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/ofdm_insert_preamble_tagged.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_insert_preamble_tagged_pydoc.h>

void bind_ofdm_insert_preamble_tagged(py::module& m)
{

    using ofdm_insert_preamble_tagged = gr::ieee802_11::ofdm_insert_preamble_tagged;


    py::class_<ofdm_insert_preamble_tagged,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_insert_preamble_tagged>>(
        m, "ofdm_insert_preamble_tagged", D(ofdm_insert_preamble_tagged))

        .def(py::init(&ofdm_insert_preamble_tagged::make),
             py::arg("fft_length"),
             py::arg("preamble"),
             D(ofdm_insert_preamble_tagged, make))


        ;
}
