/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(uav_system.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f6bdb4c59d731707da3388cdf94d318b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ieee802_11/uav_system.h>
// pydoc.h is automatically generated in the build directory
#include <uav_system_pydoc.h>

void bind_uav_system(py::module& m)
{

    using uav_system = gr::ieee802_11::uav_system;


    py::class_<uav_system, gr::block, gr::basic_block, std::shared_ptr<uav_system>>(
        m, "uav_system", D(uav_system))

        .def(py::init(&uav_system::make),
             py::arg("src"),
             py::arg("period_ms"),
             py::arg("master"),
             D(uav_system, make))


        ;
}
